/* File: _f_flipchemmodule.c
 * This file is auto-generated with f2py (version:1.26.4).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Sep 22 11:34:17 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_f_flipchem_error;
static PyObject *_f_flipchem_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _f_flipchem_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _f_flipchem_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
float_from_pyobj(float* v, PyObject *obj, const char *errmess)
{
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(chemion,CHEMION)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,int*);
extern void F_FUNC(getltsza,GETLTSZA)(int*,float*,float*,float*,float*,float*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** chemion **********************************/
static char doc_f2py_rout__f_flipchem_chemion[] = "\
oxplus,o2plus,noplus,n2plus,nplus,nno,n2d,photoprd,iters = chemion(jprint,alt,f107,f107a,te,ti,tn,oxn,o2n,n2n,hen,hn,user_no,n4s,ne,user_oplus,szad)\n\nWrapper for ``chemion``.\
\n\nParameters\n----------\n"
"jprint : input int\n"
"alt : input float\n"
"f107 : input float\n"
"f107a : input float\n"
"te : input float\n"
"ti : input float\n"
"tn : input float\n"
"oxn : input float\n"
"o2n : input float\n"
"n2n : input float\n"
"hen : input float\n"
"hn : input float\n"
"user_no : input float\n"
"n4s : input float\n"
"ne : input float\n"
"user_oplus : input float\n"
"szad : input float\n"
"\nReturns\n-------\n"
"oxplus : float\n"
"o2plus : float\n"
"noplus : float\n"
"n2plus : float\n"
"nplus : float\n"
"nno : float\n"
"n2d : float\n"
"photoprd : float\n"
"iters : int";
/* extern void F_FUNC(chemion,CHEMION)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,int*); */
static PyObject *f2py_rout__f_flipchem_chemion(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int jprint = 0;
    PyObject *jprint_capi = Py_None;
    float alt = 0;
    PyObject *alt_capi = Py_None;
    float f107 = 0;
    PyObject *f107_capi = Py_None;
    float f107a = 0;
    PyObject *f107a_capi = Py_None;
    float te = 0;
    PyObject *te_capi = Py_None;
    float ti = 0;
    PyObject *ti_capi = Py_None;
    float tn = 0;
    PyObject *tn_capi = Py_None;
    float oxn = 0;
    PyObject *oxn_capi = Py_None;
    float o2n = 0;
    PyObject *o2n_capi = Py_None;
    float n2n = 0;
    PyObject *n2n_capi = Py_None;
    float hen = 0;
    PyObject *hen_capi = Py_None;
    float hn = 0;
    PyObject *hn_capi = Py_None;
    float user_no = 0;
    PyObject *user_no_capi = Py_None;
    float n4s = 0;
    PyObject *n4s_capi = Py_None;
    float ne = 0;
    PyObject *ne_capi = Py_None;
    float user_oplus = 0;
    PyObject *user_oplus_capi = Py_None;
    float szad = 0;
    PyObject *szad_capi = Py_None;
    float oxplus = 0;
    float o2plus = 0;
    float noplus = 0;
    float n2plus = 0;
    float nplus = 0;
    float nno = 0;
    float n2d = 0;
    float photoprd = 0;
    int iters = 0;
    static char *capi_kwlist[] = {"jprint","alt","f107","f107a","te","ti","tn","oxn","o2n","n2n","hen","hn","user_no","n4s","ne","user_oplus","szad",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOOOO|:_f_flipchem.chemion",\
        capi_kwlist,&jprint_capi,&alt_capi,&f107_capi,&f107a_capi,&te_capi,&ti_capi,&tn_capi,&oxn_capi,&o2n_capi,&n2n_capi,&hen_capi,&hn_capi,&user_no_capi,&n4s_capi,&ne_capi,&user_oplus_capi,&szad_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable jprint */
        f2py_success = int_from_pyobj(&jprint,jprint_capi,"_f_flipchem.chemion() 1st argument (jprint) can't be converted to int");
    if (f2py_success) {
    /* Processing variable alt */
        f2py_success = float_from_pyobj(&alt,alt_capi,"_f_flipchem.chemion() 2nd argument (alt) can't be converted to float");
    if (f2py_success) {
    /* Processing variable f107 */
        f2py_success = float_from_pyobj(&f107,f107_capi,"_f_flipchem.chemion() 3rd argument (f107) can't be converted to float");
    if (f2py_success) {
    /* Processing variable f107a */
        f2py_success = float_from_pyobj(&f107a,f107a_capi,"_f_flipchem.chemion() 4th argument (f107a) can't be converted to float");
    if (f2py_success) {
    /* Processing variable te */
        f2py_success = float_from_pyobj(&te,te_capi,"_f_flipchem.chemion() 5th argument (te) can't be converted to float");
    if (f2py_success) {
    /* Processing variable ti */
        f2py_success = float_from_pyobj(&ti,ti_capi,"_f_flipchem.chemion() 6th argument (ti) can't be converted to float");
    if (f2py_success) {
    /* Processing variable tn */
        f2py_success = float_from_pyobj(&tn,tn_capi,"_f_flipchem.chemion() 7th argument (tn) can't be converted to float");
    if (f2py_success) {
    /* Processing variable oxn */
        f2py_success = float_from_pyobj(&oxn,oxn_capi,"_f_flipchem.chemion() 8th argument (oxn) can't be converted to float");
    if (f2py_success) {
    /* Processing variable o2n */
        f2py_success = float_from_pyobj(&o2n,o2n_capi,"_f_flipchem.chemion() 9th argument (o2n) can't be converted to float");
    if (f2py_success) {
    /* Processing variable n2n */
        f2py_success = float_from_pyobj(&n2n,n2n_capi,"_f_flipchem.chemion() 10th argument (n2n) can't be converted to float");
    if (f2py_success) {
    /* Processing variable hen */
        f2py_success = float_from_pyobj(&hen,hen_capi,"_f_flipchem.chemion() 11st argument (hen) can't be converted to float");
    if (f2py_success) {
    /* Processing variable hn */
        f2py_success = float_from_pyobj(&hn,hn_capi,"_f_flipchem.chemion() 12nd argument (hn) can't be converted to float");
    if (f2py_success) {
    /* Processing variable user_no */
        f2py_success = float_from_pyobj(&user_no,user_no_capi,"_f_flipchem.chemion() 13rd argument (user_no) can't be converted to float");
    if (f2py_success) {
    /* Processing variable n4s */
        f2py_success = float_from_pyobj(&n4s,n4s_capi,"_f_flipchem.chemion() 14th argument (n4s) can't be converted to float");
    if (f2py_success) {
    /* Processing variable ne */
        f2py_success = float_from_pyobj(&ne,ne_capi,"_f_flipchem.chemion() 15th argument (ne) can't be converted to float");
    if (f2py_success) {
    /* Processing variable user_oplus */
        f2py_success = float_from_pyobj(&user_oplus,user_oplus_capi,"_f_flipchem.chemion() 16th argument (user_oplus) can't be converted to float");
    if (f2py_success) {
    /* Processing variable szad */
        f2py_success = float_from_pyobj(&szad,szad_capi,"_f_flipchem.chemion() 17th argument (szad) can't be converted to float");
    if (f2py_success) {
    /* Processing variable oxplus */
    /* Processing variable o2plus */
    /* Processing variable noplus */
    /* Processing variable n2plus */
    /* Processing variable nplus */
    /* Processing variable nno */
    /* Processing variable n2d */
    /* Processing variable photoprd */
    /* Processing variable iters */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&jprint,&alt,&f107,&f107a,&te,&ti,&tn,&oxn,&o2n,&n2n,&hen,&hn,&user_no,&n4s,&ne,&user_oplus,&szad,&oxplus,&o2plus,&noplus,&n2plus,&nplus,&nno,&n2d,&photoprd,&iters);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("ffffffffi",oxplus,o2plus,noplus,n2plus,nplus,nno,n2d,photoprd,iters);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable iters */
    /* End of cleaning variable photoprd */
    /* End of cleaning variable n2d */
    /* End of cleaning variable nno */
    /* End of cleaning variable nplus */
    /* End of cleaning variable n2plus */
    /* End of cleaning variable noplus */
    /* End of cleaning variable o2plus */
    /* End of cleaning variable oxplus */
    } /*if (f2py_success) of szad*/
    /* End of cleaning variable szad */
    } /*if (f2py_success) of user_oplus*/
    /* End of cleaning variable user_oplus */
    } /*if (f2py_success) of ne*/
    /* End of cleaning variable ne */
    } /*if (f2py_success) of n4s*/
    /* End of cleaning variable n4s */
    } /*if (f2py_success) of user_no*/
    /* End of cleaning variable user_no */
    } /*if (f2py_success) of hn*/
    /* End of cleaning variable hn */
    } /*if (f2py_success) of hen*/
    /* End of cleaning variable hen */
    } /*if (f2py_success) of n2n*/
    /* End of cleaning variable n2n */
    } /*if (f2py_success) of o2n*/
    /* End of cleaning variable o2n */
    } /*if (f2py_success) of oxn*/
    /* End of cleaning variable oxn */
    } /*if (f2py_success) of tn*/
    /* End of cleaning variable tn */
    } /*if (f2py_success) of ti*/
    /* End of cleaning variable ti */
    } /*if (f2py_success) of te*/
    /* End of cleaning variable te */
    } /*if (f2py_success) of f107a*/
    /* End of cleaning variable f107a */
    } /*if (f2py_success) of f107*/
    /* End of cleaning variable f107 */
    } /*if (f2py_success) of alt*/
    /* End of cleaning variable alt */
    } /*if (f2py_success) of jprint*/
    /* End of cleaning variable jprint */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of chemion *******************************/

/********************************** getltsza **********************************/
static char doc_f2py_rout__f_flipchem_getltsza[] = "\
sat,sza,dec = getltsza(iday,sec,glatr,glond)\n\nWrapper for ``getltsza``.\
\n\nParameters\n----------\n"
"iday : input int\n"
"sec : input float\n"
"glatr : input float\n"
"glond : input float\n"
"\nReturns\n-------\n"
"sat : float\n"
"sza : float\n"
"dec : float";
/* extern void F_FUNC(getltsza,GETLTSZA)(int*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout__f_flipchem_getltsza(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int iday = 0;
    PyObject *iday_capi = Py_None;
    float sec = 0;
    PyObject *sec_capi = Py_None;
    float glatr = 0;
    PyObject *glatr_capi = Py_None;
    float glond = 0;
    PyObject *glond_capi = Py_None;
    float sat = 0;
    float sza = 0;
    float dec = 0;
    static char *capi_kwlist[] = {"iday","sec","glatr","glond",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:_f_flipchem.getltsza",\
        capi_kwlist,&iday_capi,&sec_capi,&glatr_capi,&glond_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable iday */
        f2py_success = int_from_pyobj(&iday,iday_capi,"_f_flipchem.getltsza() 1st argument (iday) can't be converted to int");
    if (f2py_success) {
    /* Processing variable sec */
        f2py_success = float_from_pyobj(&sec,sec_capi,"_f_flipchem.getltsza() 2nd argument (sec) can't be converted to float");
    if (f2py_success) {
    /* Processing variable glatr */
        f2py_success = float_from_pyobj(&glatr,glatr_capi,"_f_flipchem.getltsza() 3rd argument (glatr) can't be converted to float");
    if (f2py_success) {
    /* Processing variable glond */
        f2py_success = float_from_pyobj(&glond,glond_capi,"_f_flipchem.getltsza() 4th argument (glond) can't be converted to float");
    if (f2py_success) {
    /* Processing variable sat */
    /* Processing variable sza */
    /* Processing variable dec */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&iday,&sec,&glatr,&glond,&sat,&sza,&dec);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("fff",sat,sza,dec);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable dec */
    /* End of cleaning variable sza */
    /* End of cleaning variable sat */
    } /*if (f2py_success) of glond*/
    /* End of cleaning variable glond */
    } /*if (f2py_success) of glatr*/
    /* End of cleaning variable glatr */
    } /*if (f2py_success) of sec*/
    /* End of cleaning variable sec */
    } /*if (f2py_success) of iday*/
    /* End of cleaning variable iday */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of getltsza ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_euvprd_def[] = {
  {"euvion",2,{{3,12}},NPY_FLOAT, 1},
  {"pexcit",2,{{3,12}},NPY_FLOAT, 1},
  {"pepion",2,{{3,12}},NPY_FLOAT, 1},
  {"othpr1",1,{{6}},NPY_FLOAT, 1},
  {"othpr2",1,{{6}},NPY_FLOAT, 1},
  {NULL}
};
static void f2py_setup_euvprd(char *euvion,char *pexcit,char *pepion,char *othpr1,char *othpr2) {
  int i_f2py=0;
  f2py_euvprd_def[i_f2py++].data = euvion;
  f2py_euvprd_def[i_f2py++].data = pexcit;
  f2py_euvprd_def[i_f2py++].data = pepion;
  f2py_euvprd_def[i_f2py++].data = othpr1;
  f2py_euvprd_def[i_f2py++].data = othpr2;
}
extern void F_FUNC(f2pyiniteuvprd,F2PYINITEUVPRD)(void(*)(char*,char*,char*,char*,char*));
static void f2py_init_euvprd(void) {
  F_FUNC(f2pyiniteuvprd,F2PYINITEUVPRD)(f2py_setup_euvprd);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"chemion",-1,{{-1}},0,0,(char *)  F_FUNC(chemion,CHEMION),  (f2py_init_func)f2py_rout__f_flipchem_chemion,doc_f2py_rout__f_flipchem_chemion},
    {"getltsza",-1,{{-1}},0,0,(char *)  F_FUNC(getltsza,GETLTSZA),  (f2py_init_func)f2py_rout__f_flipchem_getltsza,doc_f2py_rout__f_flipchem_getltsza},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_f_flipchem",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__f_flipchem(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _f_flipchem_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _f_flipchem (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_f_flipchem' is auto-generated with f2py (version:1.26.4).\nFunctions:\n"
"    oxplus,o2plus,noplus,n2plus,nplus,nno,n2d,photoprd,iters = chemion(jprint,alt,f107,f107a,te,ti,tn,oxn,o2n,n2n,hen,hn,user_no,n4s,ne,user_oplus,szad)\n"
"    sat,sza,dec = getltsza(iday,sec,glatr,glond)\n"
"COMMON blocks:\n""  /euvprd/ euvion(3,12),pexcit(3,12),pepion(3,12),othpr1(6),othpr2(6)\n"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _f_flipchem_error = PyErr_NewException ("_f_flipchem.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__f_flipchem_error", _f_flipchem_error);
    Py_DECREF(_f_flipchem_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  tmp = PyFortranObject_New(f2py_euvprd_def,f2py_init_euvprd);
  if (tmp == NULL) return NULL;
  if (F2PyDict_SetItemString(d, "euvprd", tmp) == -1) return NULL;
  Py_DECREF(tmp);
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_f_flipchem");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
