C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.26.4)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyiniteuvprd(setupfunc)
      external setupfunc
      real euvion(3,12)
      real pexcit(3,12)
      real pepion(3,12)
      real othpr1(6)
      real othpr2(6)
      common /euvprd/ euvion,pexcit,pepion,othpr1,othpr2
      call setupfunc(euvion,pexcit,pepion,othpr1,othpr2)
      end


